/**
 * English translations for the AgentHub app
 * Values can be:
 * - String constants for static text
 * - Functions with typed object parameters for dynamic text
 */

/**
 * English plural helper function
 * @param options - Object containing count, singular, and plural forms
 * @returns The appropriate form based on count
 */
function plural({ count, singular, plural }: { count: number; singular: string; plural: string }): string {
    return count === 1 ? singular : plural;
}

export const en = {
    tabs: {
        // Tab navigation labels
        sessions: 'Terminals',
        machines: 'Devices',
        settings: 'Settings',
    },

    common: {
        // Simple string constants
        cancel: 'Cancel',
        authenticate: 'Authenticate',
        save: 'Save',
        saveAs: 'Save As',
        error: 'Error',
        success: 'Success',
        ok: 'OK',
        continue: 'Continue',
        back: 'Back',
        create: 'Create',
        rename: 'Rename',
        reset: 'Reset',
        logout: 'Logout',
        yes: 'Yes',
        no: 'No',
        discard: 'Discard',
        version: 'Version',
        copied: 'Copied',
        copy: 'Copy',
        scanning: 'Scanning...',
        urlPlaceholder: 'https://example.com',
        home: 'Home',
        message: 'Message',
        files: 'Files',
        fileTransfers: 'File transfers',
        fileViewer: 'File Viewer',
        loading: 'Loading...',
        retry: 'Retry',
        delete: 'Delete',
        optional: 'optional',
        details: 'Details',
        done: 'Done',
        confirm: 'Confirm',
        archive: 'Archive',
        resume: 'Resume',
        close: 'Close',
        backAgainToExit: 'Press back again to exit AgentHub',
        unknownError: 'Unknown error',
        attachmentUploadFailedTitle: 'Attachment upload failed',
        attachmentUploadFailedMessage: 'The image could not be uploaded securely. Your content was kept; check your connection and try again.',
        attachmentUploadPartialTitle: 'Some attachments failed',
        attachmentUploadPartialMessage: ({ count }: { count: number }) => `${count} image${count === 1 ? '' : 's'} could not be uploaded. The remaining attachments and message were sent.`,
        attachmentAccessibilityLabel: ({ name }: { name: string }) => `Attachment: ${name}`,
        sessionControlObserver: 'Read-only: another device controls this session',
        sessionControlController: 'This device controls the session',
        sessionControlRelease: 'Release control',
        sessionControlClaim: 'Take control',
        sessionControlClaimFailed: 'This session is controlled by another device',
    },

    profile: {
        userProfile: 'User Profile',
        details: 'Details',
        firstName: 'First Name',
        lastName: 'Last Name',
        username: 'Username',
        status: 'Status',
    },

    status: {
        connected: 'connected',
        connecting: 'connecting',
        disconnected: 'disconnected',
        error: 'error',
        online: 'online',
        offline: 'offline',
        lastSeen: ({ time }: { time: string }) => `last seen ${time}`,
        permissionRequired: 'permission required',
        activeNow: 'Active now',
        unknown: 'unknown',
    },

    sessionThinking: {
        working: 'Working',
        thinking: 'Thinking',
        reviewingContext: 'Reviewing context',
        checkingChanges: 'Checking changes',
        preparingNextStep: 'Preparing the next step',
        readingToolOutput: 'Reading tool output',
        refiningJudgment: 'Refining the judgment',
        composingReply: 'Composing a reply',
        calibratingDirection: 'Calibrating the direction',
        completingThoughts: 'Completing the thought',
        approachingAnswer: 'Getting closer to the answer',
        polishingExpression: 'Polishing the response',
    },

    time: {
        justNow: 'just now',
        minutesAgo: ({ count }: { count: number }) => `${count} minute${count !== 1 ? 's' : ''} ago`,
        hoursAgo: ({ count }: { count: number }) => `${count} hour${count !== 1 ? 's' : ''} ago`,
    },

    connect: {
        restoreAccount: 'Restore Account',
        enterSecretKey: 'Please enter a secret key',
        invalidSecretKey: 'Invalid secret key. Please check and try again.',
        enterUrlManually: 'Connect with auth link',
    },

    settings: {
        title: 'Settings',
        connectedAccounts: 'Connected Accounts',
        connectAccount: 'Connect account',
        apiCredentials: 'API Credentials',
        apiCredentialsSubtitle: 'Manage API keys for remote sessions',
        credentials: 'Credentials',
        github: 'GitHub',
        machines: 'Machines',
        showOfflineMachines: ({ count }: { count: number }) => count === 1 ? 'Show 1 offline machine' : `Show ${count} offline machines`,
        hideOfflineMachines: 'Hide offline machines',
        features: 'Features',
        account: 'Account',
        accountSubtitle: 'Manage your account details',
        appearance: 'Appearance',
        appearanceSubtitle: 'Customize how the app looks',
        featuresTitle: 'Features',
        featuresSubtitle: 'Enable or disable app features',
        developer: 'Developer',
        developerTools: 'Developer Tools',
        about: 'About',
        aboutFooter: 'AgentHub is a Codex and Claude Code workspace client. It is fully end-to-end encrypted and your account is stored only on your device. Not affiliated with Anthropic.',
        whatsNew: 'What\'s New',
        whatsNewSubtitle: 'See the latest updates and improvements',
        reportIssue: 'Report an Issue',
        privacyPolicy: 'Privacy Policy',
        termsOfService: 'Terms of Service',
        eula: 'EULA',
        supportUs: 'Support us',
        supportUsSubtitlePro: 'Thank you for your support!',
        supportUsSubtitle: 'Support project development',
        scanQrCodeToAuthenticate: 'Scan QR code',
        githubConnected: ({ login }: { login: string }) => `Connected as @${login}`,
        connectGithubAccount: 'Connect your GitHub account',
        claudeAuthSuccess: 'Successfully connected to Claude',
        exchangingTokens: 'Exchanging tokens...',
        usage: 'Usage',
        usageSubtitle: 'View tokens, agents, models, and cache usage',
        checkForUpdates: 'Check for updates',
        checkForUpdatesSubtitle: 'Look for an available app update',
        noUpdatesAvailable: 'You are already on the latest version.',
        updateCheckUnavailable: 'Update checks are unavailable in this build.',
        updateCheckFailed: 'Unable to check for updates. Please try again later.',
        // Dynamic settings messages
        accountConnected: ({ service }: { service: string }) => `${service} account connected`,
        machineStatus: ({ name, status }: { name: string; status: 'online' | 'offline' }) =>
            `${name} is ${status}`,
        featureToggled: ({ feature, enabled }: { feature: string; enabled: boolean }) =>
            `${feature} ${enabled ? 'enabled' : 'disabled'}`,
    },

    settingsAppearance: {
        // Appearance settings screen
        theme: 'Theme',
        themeDescription: 'Choose your preferred color scheme',
        themeOptions: {
            adaptive: 'Adaptive',
            light: 'Light', 
            dark: 'Dark',
        },
        themeDescriptions: {
            adaptive: 'Match system settings',
            light: 'Always use light theme',
            dark: 'Always use dark theme',
        },
        display: 'Display',
        displayDescription: 'Control layout and spacing',
        collapseAgentWork: 'Automatically Collapse Agent Work',
        collapseAgentWorkDescription: 'After a final reply, collapse tools, file updates, and progress into a compact summary',
        inlineToolCalls: 'Inline Tool Calls',
        inlineToolCallsDescription: 'Display tool calls directly in chat messages',
        expandTodoLists: 'Expand Todo Lists',
        expandTodoListsDescription: 'Show all todos instead of just changes',
        showLineNumbersInDiffs: 'Show Line Numbers in Diffs',
        showLineNumbersInDiffsDescription: 'Display line numbers in code diffs',
        showLineNumbersInToolViews: 'Show Line Numbers in Tool Views',
        showLineNumbersInToolViewsDescription: 'Display line numbers in tool view diffs',
        wrapLinesInDiffs: 'Wrap Long Lines',
        wrapLinesInDiffsDescription: 'Wrap long lines in diffs, file text, terminal commands, and command output',
        diffStyle: 'Diff View',
        diffStyleDescription: 'Show diffs as a single column (unified) or side-by-side (split). Split view is web-only.',
        diffStyleOptions: {
            unified: 'Unified',
            split: 'Split',
        },
        alwaysShowContextSize: 'Always Show Context Size',
        alwaysShowContextSizeDescription: 'Display context usage even when not near limit',
        sessionStatusBar: 'Session status bar',
        sessionStatusBarDescription: 'Show branch, model, effort, context, and plan limits around the composer',
        sessionStatusBarHidden: 'Off',
        sessionStatusBarAbove: 'Above',
        sessionStatusBarBelow: 'Below',
        usageLimitShowRemaining: 'Show quota remaining',
        usageLimitShowRemainingDescription: 'Display plan-limit percentages as remaining instead of used',
        // Scaling
        scaling: 'Scaling',
        scalingDescription: 'Adjust the size of interface elements',
        sessionScale: 'Session List',
        chatScale: 'Chat',
        fileScale: 'File Preview',
        fileListScale: 'File Lists',
        deviceScale: 'Devices',
        settingsScale: 'Lists & Settings',
        scaleDefault: 'Default',
        scaleLevelXXS: 'XS',
        scaleLevelXS: 'S',
        scaleLevelS: 'M',
        scaleLevelM: 'L',
        scaleLevelL: 'XL',
        previewLabel: 'Preview',
    },

    previewSamples: {
        chatWorkspaceTitle: 'AgentHub workspace',
        chatWorkspaceSubtitle: 'Amber Crystal chat preview',
        chatUserPrompt: 'Check the authentication in the sign-in flow',
        chatAgentReview: 'I’ll inspect the current implementation, focusing on session.verify() and credential refresh in the middleware.',
        chatEdit: 'Edit',
        chatPlanMode: 'Switched to plan mode',
        chatAnalysisComplete: 'Analysis complete',
        chatRecommendation: 'The middleware token refresh needs a controlled retry and a logged failure reason.',
        favoriteDevices: ({ count }: { count: number }) => count === 1 ? '1 favorite device' : `${count} favorite devices`,
        developmentWorkstation: 'Development workstation',
        buildServer: 'Build server',
        fileDirectory: 'Folder',
        sessionMobileClient: 'Mobile client',
        sessionFixAuth: 'Fix sign-in authentication',
        sessionProfile: 'Finish the profile page',
        sessionCache: 'Refactor the local cache query',
        sessionApiService: 'API service',
        sessionTokenRefresh: 'Implement token refresh',
        sessionRateLimit: 'Add rate-limit middleware',
        sessionApiDocs: 'Update API documentation',
        sessionCors: 'Fix production CORS configuration',
        settingsSection: 'Appearance & account',
        credentialsSaved: ({ count }: { count: number }) => count === 1 ? '1 saved' : `${count} saved`,
    },

    settingsFeatures: {
        // Features settings screen
        experiments: 'Experiments',
        experimentsDescription: 'Enable experimental features that are still in development. These features may be unstable or change without notice.',
        experimentalFeatures: 'Experimental Features',
        experimentalFeaturesEnabled: 'Experimental features enabled',
        experimentalFeaturesDisabled: 'Using stable features only',
        webFeatures: 'Web Features',
        webFeaturesDescription: 'Features available only in the web version of the app.',
        enterToSend: 'Enter to Send',
        enterToSendEnabled: 'Press Enter to send (Shift+Enter for a new line)',
        enterToSendDisabled: 'Enter inserts a new line',
        commandPalette: 'Command Palette',
        commandPaletteEnabled: 'Press ⌘K to open',
        commandPaletteDisabled: 'Quick command access disabled',
        markdownCopyV2: 'Markdown Copy v2',
        markdownCopyV2Subtitle: 'Long press opens copy modal',
        hideInactiveSessions: 'Hide ended sessions',
        hideInactiveSessionsSubtitle: 'Hide ended AgentHub sessions from project lists',
        privacy: 'Privacy',
        privacyDescription: 'Completely disables all analytics and telemetry. No data will be sent to any tracking service.',
        disableAnalytics: 'Disable Analytics',
        analyticsDisabled: 'All tracking and telemetry disabled',
        analyticsEnabled: 'Anonymous usage analytics active',
        interfaceTitle: 'Interface',
        interfaceFooter: 'Optional panels and layout elements.',
        fileDiffsSidebar: 'File Diffs Sidebar',
        fileDiffsSidebarSubtitle: 'Show git changes next to the chat on desktop',
        resumeSessionFeature: 'Resume Session',
        resumeSessionFeatureSubtitle: 'Resume disconnected Claude Code and Codex sessions via the machine daemon',
    },

    errors: {
        networkError: 'Network error occurred',
        serverError: 'Server error occurred',
        unknownError: 'An unknown error occurred',
        connectionTimeout: 'Connection timed out',
        authenticationFailed: 'Authentication failed',
        permissionDenied: 'Permission denied',
        fileNotFound: 'File not found',
        invalidFormat: 'Invalid format',
        operationFailed: 'Operation failed',
        tryAgain: 'Please try again',
        contactSupport: 'Contact support if the problem persists',
        sessionNotFound: 'Session not found',
        oauthInitializationFailed: 'Failed to initialize OAuth flow',
        tokenStorageFailed: 'Failed to store authentication tokens',
        oauthStateMismatch: 'Security validation failed. Please try again',
        tokenExchangeFailed: 'Failed to exchange authorization code',
        oauthAuthorizationDenied: 'Authorization was denied',
        webViewLoadFailed: 'Failed to load authentication page',
        failedToLoadProfile: 'Failed to load user profile',
        userNotFound: 'User not found',
        sessionDeleted: 'Session has been deleted',
        sessionDeletedDescription: 'This session has been permanently removed',

        // Error functions with context
        fieldError: ({ field, reason }: { field: string; reason: string }) =>
            `${field}: ${reason}`,
        validationError: ({ field, min, max }: { field: string; min: number; max: number }) =>
            `${field} must be between ${min} and ${max}`,
        retryIn: ({ seconds }: { seconds: number }) =>
            `Retry in ${seconds} ${seconds === 1 ? 'second' : 'seconds'}`,
        errorWithCode: ({ message, code }: { message: string; code: number | string }) =>
            `${message} (Error ${code})`,
        disconnectServiceFailed: ({ service }: { service: string }) => 
            `Failed to disconnect ${service}`,
        connectServiceFailed: ({ service }: { service: string }) =>
            `Failed to connect ${service}. Please try again.`,
        searchFailed: 'Search failed. Please try again.',
    },

    newSession: {
        title: 'Start New Session',
        machineOffline: 'Machine is offline',
        switchMachinesHint: '• Switch machines by clicking on the machine above',
        browseFolders: 'Browse Folders',
        selectThisFolder: 'Select This Folder',
        parentFolder: 'Up One Level',
        emptyFolder: 'This folder is empty',
        noAccess: 'No access to this directory',
        folderNotFound: 'Directory does not exist',
        showHidden: 'Show Hidden',
        switchToTextInput: 'Switch to text input',
        machine: 'Machine',
        project: 'Project',
        searchMachines: 'search machines...',
        worktree: 'Worktree',
        searchWorktrees: 'search worktrees...',
        noWorktree: 'no worktree',
        newWorktree: 'new worktree',
        searchFallback: 'search...',
        selectMachine: 'Please select a machine',
        machineOfflineShort: 'Machine is offline',
        failedToCreateWorktree: 'Failed to create worktree',
        createDirectory: 'Create Directory?',
        createDirectoryMessage: ({ path }: { path: string }) => `The directory ${path} does not exist. Would you like to create it?`,
        failedToStartSession: 'Failed to start session',
        creatingSession: 'Creating session...',
        creatingSessionDescription: 'Starting the remote agent and syncing the latest status.',
        newFolder: 'New Folder',
        newFolderName: 'Folder name',
        createFolderError: 'Failed to create folder',
        selectCredential: 'Credential',
        searchCredentials: 'search credentials...',
        useHostCredentials: 'Use host credentials',
        hostHasLocalCredentials: 'This device has local credentials',
        setupTitle: 'Set the required context',
        setupSubtitle: 'Device, folder, and agent before launch.',
        advancedSettings: 'Advanced settings',
        browseFolderAccessibility: ({ folder }: { folder: string }) => `Browse folder: ${folder}`,
        selectMachineAccessibility: ({ machine }: { machine: string }) => `Select device: ${machine}`,
        switchAgentAccessibility: ({ agent }: { agent: string }) => `Switch agent: ${agent}`,
        switchPermissionAccessibility: ({ mode }: { mode: string }) => `Switch permission mode: ${mode}`,
        selectWorktreeAccessibility: ({ worktree }: { worktree: string }) => `Select worktree: ${worktree}`,
        setup: {
            machine: {
                title: 'Device',
                description: 'Choose which computer will start this session.',
            },
            machineOffline: {
                description: 'This device is offline. Choose an online device before starting.',
            },
            path: {
                title: 'Working folder',
                description: 'AgentHub uses this project folder as the starting context.',
            },
            agent: {
                title: 'Agent and model',
                description: 'Switch the CLI agent, model profile, and reasoning effort.',
            },
            permission: {
                title: 'Permission mode',
                description: 'Controls whether edits and commands need confirmation.',
            },
            credential: {
                title: 'Credentials',
                description: 'Use host credentials or choose a saved API credential.',
            },
            worktree: {
                title: 'Git worktree',
                description: 'Start in the current folder, an existing worktree, or a new branch.',
            },
        },
    },

    credentials: {
        title: 'API Credentials',
        addCredential: 'Add Credential',
        editCredential: 'Edit Credential',
        deleteCredential: 'Delete Credential',
        deleteConfirm: 'Are you sure you want to delete this credential?',
        deleteCredentialLabel: ({ label }: { label: string }) => `Delete ${label}`,
        loadFailed: 'Could not load credentials. Check your connection and try again.',
        deleteFailed: 'Could not delete this credential. It has not been removed.',
        saveFailed: 'Could not save this credential. Your changes are still here.',
        label: 'Label',
        labelPlaceholder: 'e.g., Production API',
        agentType: 'Agent Type',
        apiKey: 'API Key',
        apiKeyPlaceholder: 'Enter your API key',
        apiKeyUnchanged: 'Leave blank to keep the current key',
        baseUrl: 'Base URL',
        baseUrlPlaceholder: 'https://api.example.com (optional)',
        modelOverrides: 'Model Overrides',
        modelPlaceholder: 'e.g., claude-sonnet-4-20250514',
        noCredentials: 'No credentials configured',
        noCredentialsSubtitle: 'Add an API credential to use when spawning remote sessions',
        lastUsed: ({ time }: { time: string }) => `Last used: ${time}`,
        saveSuccess: 'Credential saved',
        deleteSuccess: 'Credential deleted',
        validationLabelRequired: 'Label is required',
        validationApiKeyRequired: 'API key is required',
        anthropicModel: 'Default Model',
        anthropicHaikuModel: 'Haiku Model',
        anthropicSonnetModel: 'Sonnet Model',
        anthropicOpusModel: 'Opus Model',
        anthropicReasoningModel: 'Reasoning Model',
    },

    slashCommands: {
        compact: 'Compact the conversation history',
        clear: 'Clear the conversation',
        goal: 'Set a session goal',
        mcp: 'Show connected MCP servers',
        skills: 'Show available skills',
        runCommand: ({ command }: { command: string }) => `Run the /${command} command`,
        useSkill: ({ skill }: { skill: string }) => `Use the ${skill} skill: `,
        skillFrontend: 'Design, review, and refine frontend UI details',
        skillDebug: 'Diagnose issues and plan a repair path',
        skillPlan: 'Break complex work into an executable plan',
        skillReview: 'Review code for risks, regressions, and missing tests',
        skillTest: 'Add tests and verification around the change',
        skillGit: 'Work with branches, commits, worktrees, and merges',
        skillGeneric: 'Use this skill for its specialized task area',
        help: 'Show available commands',
        reset: 'Reset the session',
        export: 'Export conversation',
        debug: 'Show debug information',
        status: 'Show connection status',
        stop: 'Stop current operation',
        abort: 'Abort current operation',
        cancel: 'Cancel current operation',
        groups: {
            common: 'Common',
            builtin: 'Built-in',
            extension: 'Extensions',
        },
    },


    sessionHistory: {
        // Used by session history screen
        title: 'Session History',
        empty: 'No sessions found',
        today: 'Today',
        yesterday: 'Yesterday',
        daysAgo: ({ count }: { count: number }) => `${count} ${count === 1 ? 'day' : 'days'} ago`,
        viewAll: 'View all sessions',
    },

    session: {
        inputPlaceholder: 'Type a message ...',
        inactiveArchived: 'This session is inactive.',
        resumeFromTerminal: 'To resume it from the terminal:',
        permissionHint: 'Permissions shown in terminal only. Reset or send a message to control from app.',
        noCommandOutput: '[Command completed with no output]',
        sandboxed: '(sandboxed)',
        newSessionPlaceholder: 'What would you like to work on?',
        importOfficialTitle: 'Taking over the computer session',
        importOfficialDescription: 'Importing the conversation, restoring context, and syncing the current state. This session is unavailable until the import finishes.',
        forkSession: 'Fork complete session',
        duplicateSession: 'Fork from a message',
        duplicateMessageHint: 'Long press to create a branch from this message',
        duplicateSheetTitle: 'Create a conversation branch',
        duplicateSheetSubtitle: 'Choose the user message that the new independent session should include through.',
        duplicateSheetEmpty: 'No valid user-message rewind points were found.',
        duplicateSheetConfirm: 'Create branch',
        forkErrorMissingMetadata: 'This session is missing the machine or provider metadata required to fork it.',
        forkErrorGeneric: 'Unable to create the conversation branch.',
        forkMachineOffline: 'The source machine must be online to create a conversation branch.',
    },

    commandPalette: {
        placeholder: 'Type a command or search...',
    },

    server: {
        // Used by Server Configuration screen (app/(app)/server.tsx)
        serverConfiguration: 'Server Configuration',
        enterServerUrl: 'Please enter a server URL',
        notValidAgentHubServer: 'Not a valid AgentHub Server',
        changeServer: 'Change Server',
        continueWithServer: 'Continue with this server?',
        resetToDefault: 'Reset to Default',
        resetServerDefault: 'Reset server to default?',
        validating: 'Validating...',
        validatingServer: 'Validating server...',
        serverReturnedError: 'Server returned an error',
        failedToConnectToServer: 'Failed to connect to server',
        currentlyUsingCustomServer: 'Currently using custom server',
        customServerUrlLabel: 'Custom Server URL',
        advancedFeatureFooter: "This is an advanced feature. Only change the server if you know what you're doing. You will need to log out and log in again after changing servers."
    },

    sessionInfo: {
        // Used by Session Info screen (app/(app)/session/[id]/info.tsx)
        killSession: 'Kill Session',
        killSessionConfirm: 'Are you sure you want to terminate this session?',
        archiveSession: 'Move out of workspace',
        archiveSessionConfirm: 'Move this session out of the workspace?',
        agentHubSessionIdCopied: 'AgentHub Session ID copied to clipboard',
        failedToCopySessionId: 'Failed to copy AgentHub Session ID',
        agentHubSessionId: 'AgentHub Session ID',
        claudeCodeSessionId: 'Claude Code Session ID',
        claudeCodeSessionIdCopied: 'Claude Code Session ID copied to clipboard',
        codexThreadId: 'Codex Thread ID',
        codexThreadIdCopied: 'Codex Thread ID copied to clipboard',
        aiProvider: 'AI Provider',
        failedToCopyClaudeCodeSessionId: 'Failed to copy Claude Code Session ID',
        failedToCopyCodexThreadId: 'Failed to copy Codex Thread ID',
        metadataCopied: 'Session metadata copied to clipboard',
        failedToCopyMetadata: 'Failed to copy session metadata',
        failedToKillSession: 'Failed to kill session',
        failedToArchiveSession: 'Failed to move session out of workspace',
        connectionStatus: 'Connection Status',
        created: 'Created',
        lastUpdated: 'Last Updated',
        sequence: 'Sequence',
        quickActions: 'Quick Actions',
        viewMachine: 'View Machine',
        viewMachineSubtitle: 'View machine details and sessions',
        resumeSession: 'Resume Session',
        resumeSessionSubtitle: 'Resume this session on the same machine',
        resumeSessionSameMachineOnly: 'This session can only be resumed on the same machine it started on.',
        resumeSessionMachineOffline: 'This machine is offline. Resume is only available while it is online.',
        resumeSessionNeedsAgentHubAgent: 'Resume is unavailable on this machine. Run `agenthub-agent auth login` to enable it.',
        resumeSessionMissingMachine: 'This session is missing its machine metadata, so it cannot be resumed.',
        resumeSessionMissingBackendId: 'This session does not have a resumable Claude or Codex identifier.',
        resumeSessionUnexpectedDirectoryPrompt: 'Resume cannot create directories. Start the session manually from its original path.',
        killSessionSubtitle: 'Immediately terminate the session',
        archiveSessionSubtitle: 'Stop it and remove it from the current workspace. You can still find it in archived sessions.',
        lifecycleStopping: 'Stopping local runner…',
        lifecycleRunnerStopped: 'Local runner stopped',
        lifecycleStopTimedOut: 'Local runner stop timed out',
        lifecycleRunnerUnavailable: 'Local runner unavailable',
        lifecycleArchived: 'Archived',
        metadata: 'Metadata',
        host: 'Host',
        path: 'Path',
        operatingSystem: 'Operating System',
        processId: 'Process ID',
        agenthubHome: 'AgentHub Home',
        copyMetadata: 'Copy session metadata',
        agentState: 'Agent State',
        controlledByUser: 'Controlled by User',
        pendingRequests: 'Pending Requests',
        activity: 'Activity',
        thinking: 'Thinking',
        thinkingSince: 'Thinking Since',
        cliVersion: 'CLI Version',
        cliVersionOutdated: 'CLI Update Required',
        cliVersionOutdatedMessage: ({ currentVersion, requiredVersion }: { currentVersion: string; requiredVersion: string }) =>
            `Version ${currentVersion} installed. Update to ${requiredVersion} or later`,
        updateCliInstructions: 'Please run npm install -g @artsum/agenthub@latest',
        deleteSession: 'Permanently delete session',
        deleteSessionSubtitle: 'Delete this session and all messages. This cannot be undone.',
        deleteSessionConfirm: 'Permanently delete session?',
        deleteSessionWarning: 'This action cannot be undone. All messages and data associated with this session will be permanently deleted.',
        failedToDeleteSession: 'Failed to permanently delete session',
        sessionDeleted: 'Session deleted successfully',
        worktreeCleanupTitle: 'Delete Worktree?',
        worktreeCleanupMessage: 'The worktree has no uncommitted changes. Would you like to delete the worktree files?',
        worktreeCleanupDelete: 'Delete Worktree',
        worktreeCleanupKeep: 'Keep Files',
        mergeWorktree: 'Merge Worktree',
        mergeWorktreeSubtitle: 'Start a session to merge changes into the main branch',
        mergeWorktreeConfirmTitle: 'Merge Worktree?',
        mergeWorktreeConfirmMessage: ({ branch }: { branch: string }) =>
            `Start a new session to merge branch "${branch}" into the current branch? Claude will handle any merge conflicts.`,
        mergeWorktreeFailed: 'Failed to start merge session',
        mergeWorktreeArchiveTitle: 'Move out and clean up?',
        mergeWorktreeArchiveMessage: 'The merge session has started. Move this session out of the workspace and delete the worktree files?',
        mergeWorktreeArchiveConfirm: 'Move out and delete files',
        mergeWorktreeArchiveCancel: 'Keep Session',
        removeWorktree: 'Delete Worktree',
        removeWorktreeSubtitle: 'Remove this worktree from the repository',
        removeWorktreeFailed: 'Failed to delete worktree',
    },

    components: {
        sessionStatusBar: {
            contextUsage: ({ used, total, percent }: { used: string; total: string; percent: number }) => `Context: ${used} of ${total} tokens (${percent}%)`,
            limitFiveHour: '5-hour limit',
            limitSevenDay: '7-day limit',
            limitRemaining: ({ percent }: { percent: number }) => `${percent}% left`,
            limitResets: ({ time }: { time: string }) => `resets ${time}`,
            limitAsOf: ({ age }: { age: string }) => `updated ${age} ago`,
        },
        emptyMainScreen: {
            // Used by EmptyMainScreen component
            readyToCode: 'Ready to code?',
            installCli: 'Install the AgentHub CLI',
            runIt: 'Run it',
            scanQrCode: 'Scan the QR code',
            openCamera: 'Open Camera',
        },
        agentGoalBar: {
            currentGoal: 'Current goal',
            accessibilityLabel: ({ goal }: { goal: string }) => `Current goal: ${goal}`,
            clearGoal: 'Clear goal',
            stopGoal: 'Stop goal',
            editGoal: 'Edit goal',
        },
        emptyMessages: {
            noMessages: 'No messages yet',
            created: ({ time }: { time: string }) => `Created ${time}`,
        },
        emptySessionsTablet: {
            noActiveSessions: 'No active sessions',
            startNewDescription: 'Start a new session on any of your connected machines.',
            startNewSession: 'Start New Session',
            openTerminalHint: 'Open a new terminal on your computer to start session.',
        },
        pathPicker: {
            enterProjectPath: 'Enter project path',
            recent: 'Recent',
            noRecentProjects: 'No recent projects yet',
            usingCustomPath: 'Using custom path above',
        },
        inlineDiff: {
            failedToReadFile: 'Failed to read file',
            failedToFetchDiff: 'Failed to fetch diff',
        },
        mermaid: {
            diagramLabel: 'Mermaid diagram',
            syntaxError: 'Mermaid diagram syntax error',
        },
    },

    agentInput: {
        permissionMode: {
            title: 'PERMISSION MODE',
            default: 'default permissions',
            acceptEdits: 'accept edits',
            plan: 'plan',
            dontAsk: "don't ask",
            bypassPermissions: 'yolo',
            badgeAcceptAllEdits: 'accept all edits',
            badgeBypassAllPermissions: 'yolo',
            badgePlanMode: 'plan mode',
        },
        agent: {
            claude: 'Claude',
            codex: 'Codex',
        },
        model: {
            title: 'MODEL',
            configureInCli: 'Configure models in CLI settings',
            defaultModel: 'default model',
        },
        effort: {
            title: 'EFFORT',
            low: 'low',
            medium: 'medium',
            high: 'high',
            max: 'max',
        },
        codexPermissionMode: {
            title: 'CODEX PERMISSION MODE',
            default: 'default permissions',
            readOnly: 'read-only',
            safeYolo: 'safe yolo',
            yolo: 'yolo',
            badgeReadOnly: 'read-only',
            badgeSafeYolo: 'safe yolo',
            badgeYolo: 'yolo',
        },
        codexModel: {
            title: 'CODEX MODEL',
            gpt5CodexLow: 'gpt-5-codex low',
            gpt5CodexMedium: 'gpt-5-codex medium',
            gpt5CodexHigh: 'gpt-5-codex high',
            gpt5Minimal: 'GPT-5 Minimal',
            gpt5Low: 'GPT-5 Low',
            gpt5Medium: 'GPT-5 Medium',
            gpt5High: 'GPT-5 High',
        },
        context: {
            remaining: ({ percent }: { percent: number }) => `${percent}% left`,
            compactConfirmTitle: 'Compact context?',
            compactConfirmMessage: 'This will summarize the current conversation history to free context. The session will continue after compaction.',
            compactConfirmAction: 'Compact',
        },
        suggestion: {
            fileLabel: 'FILE',
            folderLabel: 'FOLDER',
        },
        noMachinesAvailable: 'No machines',
        send: 'Send message',
    },

    machineLauncher: {
        showLess: 'Show less',
        showAll: ({ count }: { count: number }) => `Show all (${count} paths)`,
        enterCustomPath: 'Enter custom path',
        offlineUnableToSpawn: 'Unable to spawn new session, offline',
    },

    homeOverview: {
        eyebrow: 'Workspace pulse',
        title: 'Your remote workspace',
        subtitle: 'Continue recent work, check device health, or start a focused session without turning your phone into a desktop IDE.',
        loading: 'Loading your workspace…',
        deviceHealth: 'Device health',
        deviceHealthDescription: 'Availability across the devices connected to this account.',
        devicesOnline: ({ online, total }: { online: number; total: number }) => `${online} of ${total} online`,
        workspaceHealthy: 'Workspace ready',
        workspaceHealthyDescription: 'At least one device is online and ready for remote work.',
        connectionInterrupted: 'Connection interrupted',
        connectionInterruptedDescription: 'Your local workspace remains visible while AgentHub reconnects.',
        restoringConnection: 'Restoring connection',
        restoringConnectionDescription: 'AgentHub is reconnecting to your self-hosted service.',
        noDevices: 'No devices connected',
        noDevicesDescription: 'Connect the CLI on a computer before starting your first remote session.',
        noOnlineDevices: 'Devices are offline',
        noOnlineDevicesDescription: 'Bring a connected device online to start a new session.',
        viewDevices: 'View devices',
        connectionSettings: 'Connection settings',
        recentWork: 'Recent work',
        noRecentWork: 'No recent work yet',
        noRecentWorkDescription: 'Your latest sessions will appear here after you begin working.',
        sessionFallback: 'Untitled session',
        active: 'Active',
        inactive: 'Archived',
        sidebarEmptyDescription: 'Sessions will appear here as work begins.',
    },

    sidebar: {
        sessionsTitle: 'AgentHub',
        showArchived: 'Show archived',
        hideArchived: 'Hide archived',
    },

    project: {
        actions: 'Project Actions',
        editTitle: 'Edit Project',
        editSubtitle: 'Adjust the name and icon used to identify this project in the session list.',
        nameLabel: 'Project name',
        nameHint: 'Changes only the name shown in AgentHub. The folder on the device is not renamed.',
        iconHint: 'Choose an icon that makes this project easier to recognize.',
        selectIconAccessibility: ({ icon }: { icon: string }) => `Select ${icon} project icon`,
        expandMachineAccessibility: ({ machine }: { machine: string }) => `Expand ${machine}`,
        collapseMachineAccessibility: ({ machine }: { machine: string }) => `Collapse ${machine}`,
        dismissEditorAccessibility: 'Close project editor',
        chooseIcon: 'Choose Icon',
        archivedSessions: 'Archived Sessions',
        noArchivedSessions: 'No archived sessions',
        detailsTitle: 'Project Details',
        machine: 'Device',
        path: 'Path',
        projectKey: 'Project ID',
        status: 'Project status',
        visible: 'Visible',
        hidden: 'Hidden',
        branch: 'Branch',
        worktree: 'Worktree',
        activeSessionCount: 'Active Sessions',
        archivedSessionCount: 'Archived Sessions',
        computerSessionCount: 'Computer Sessions',
        gitChanges: 'Git Changes',
        noGitChanges: 'No changes',
        notAvailable: 'Not available',
        enabled: 'Enabled',
        officialThread: 'Official',
        ignoreOfficialThread: 'Hide computer session',
        computerSessions: 'Computer sessions',
        syncStatus: 'Sync status',
        takeOverComputerSession: 'Take over',
        hideComputerSession: 'Move out of workspace',
        newSession: 'New session in this project',
        endActiveSessions: 'Stop running sessions in this project',
        endActiveSessionsConfirm: ({ count }: { count: number }) => `Stop ${count} running ${plural({ count, singular: 'session', plural: 'sessions' })} in this project?`,
        noActiveSessions: 'No active sessions in this project',
        hideProject: 'Hide project',
        hideProjectConfirm: ({ activeCount, officialCount }: { activeCount: number; officialCount: number }) =>
            `Stop ${activeCount} running ${plural({ count: activeCount, singular: 'session', plural: 'sessions' })}, then hide this project after it has no active sessions${officialCount > 0 ? ` or ${officialCount} computer ${plural({ count: officialCount, singular: 'session', plural: 'sessions' })}` : ''}?`,
        hideProjectAlsoIgnoreOfficialThreads: 'Hide computer sessions too',
        hideProjectAlsoIgnoreOfficialThreadsConfirm: ({ count }: { count: number }) =>
            `This project still has ${count} computer ${plural({ count, singular: 'session', plural: 'sessions' })}. Hide them all now so the project can be hidden immediately?`,
        hideProjectApplied: 'Project is marked hidden and will disappear after active and computer sessions are cleared',
        hideProjectBlockedByOfficialThreads: ({ count }: { count: number }) =>
            `Project is marked hidden, but ${count} computer ${plural({ count, singular: 'session is', plural: 'sessions are' })} still keeping it visible. Hide those computer sessions to hide it now.`,
        resetCustomization: 'Clear project name and icon',
        resetCustomizationConfirm: 'Remove the custom name, icon, and hidden state for this project?',
        actionComplete: 'Project operation completed',
    },

    toolView: {
        input: 'Input',
        output: 'Output',
        stateRunning: 'Running',
        stateCompleted: 'Completed',
        stateError: 'Failed',
        stateUnknown: 'Status',
    },

    toolGroup: {
        editedFile: 'Edited file',
        editedFiles: ({ count }: { count: number }) => count === 1 ? 'Edited 1 file' : `Edited ${count} files`,
        readFiles: ({ count }: { count: number }) => count === 1 ? 'Read 1 file' : `Read ${count} files`,
        ranCommands: ({ count }: { count: number }) => count === 1 ? 'Ran 1 command' : `Ran ${count} commands`,
        searched: ({ count }: { count: number }) => count === 1 ? 'Searched 1 time' : `Searched ${count} times`,
        fetchedUrls: ({ count }: { count: number }) => count === 1 ? 'Fetched 1 URL' : `Fetched ${count} URLs`,
        ranTasks: ({ count }: { count: number }) => count === 1 ? 'Ran 1 task' : `Ran ${count} tasks`,
        usedTools: ({ count }: { count: number }) => count === 1 ? 'Used 1 tool' : `Used ${count} tools`,
        workedFor: ({ duration }: { duration: string }) => `Worked ${duration}`,
        errors: ({ count }: { count: number }) => count === 1 ? '1 error' : `${count} errors`,
    },

    tools: {
        fullView: {
            description: 'Description',
            inputParams: 'Input Parameters',
            output: 'Output',
            error: 'Error',
            completed: 'Tool completed successfully',
            noOutput: 'No output was produced',
            running: 'Tool is running...',
            rawJsonDevMode: 'Raw JSON (Dev Mode)',
            command: 'Command',
            status: 'Status',
            exitCode: 'Exit code',
            duration: 'Duration',
        },
        taskView: {
            initializing: 'Initializing agent...',
            moreTools: ({ count }: { count: number }) => `+${count} more ${plural({ count, singular: 'tool', plural: 'tools' })}`,
        },
        todo: {
            progressLabel: ({ completed, total, percent }: { completed: number; total: number; percent: number }) => `${completed}/${total} done · ${percent}%`,
            listBadge: ({ completed, total }: { completed: number; total: number }) => `Todo ${completed}/${total}`,
            statusCompleted: 'Done',
            statusInProgress: 'In progress',
            statusPending: 'Pending',
            priorityHigh: 'High priority',
            priorityMedium: 'Medium priority',
            priorityLow: 'Low priority',
        },
        multiEdit: {
            editNumber: ({ index, total }: { index: number; total: number }) => `Edit ${index} of ${total}`,
            replaceAll: 'Replace All',
        },
        names: {
            task: 'Task',
            terminal: 'Terminal',
            searchFiles: 'Search Files',
            search: 'Search',
            searchContent: 'Search Content',
            listFiles: 'List Files',
            planProposal: 'Plan proposal',
            readFile: 'Read File',
            editFile: 'Edit File',
            writeFile: 'Write File',
            fetchUrl: 'Fetch URL',
            readNotebook: 'Read Notebook',
            editNotebook: 'Edit Notebook',
            todoList: 'Todo List',
            webSearch: 'Web Search',
            reasoning: 'Reasoning',
            applyChanges: 'Update file',
            viewDiff: 'Current file changes',
            question: 'Question',
        },
        askUserQuestion: {
            submit: 'Submit Answer',
            multipleQuestions: ({ count }: { count: number }) => `${count} questions`,
            other: 'Other',
            otherDescription: 'Type your own answer',
            otherPlaceholder: 'Type your answer...',
        },
        desc: {
            terminalCmd: ({ cmd }: { cmd: string }) => `Terminal(cmd: ${cmd})`,
            searchPattern: ({ pattern }: { pattern: string }) => `Search(pattern: ${pattern})`,
            searchPath: ({ basename }: { basename: string }) => `Search(path: ${basename})`,
            fetchUrlHost: ({ host }: { host: string }) => `Fetch URL(url: ${host})`,
            editNotebookMode: ({ path, mode }: { path: string; mode: string }) => `Edit Notebook(file: ${path}, mode: ${mode})`,
            todoListCount: ({ count }: { count: number }) => `Todo List(count: ${count})`,
            webSearchQuery: ({ query }: { query: string }) => `Web Search(query: ${query})`,
            grepPattern: ({ pattern }: { pattern: string }) => `grep(pattern: ${pattern})`,
            multiEditEdits: ({ path, count }: { path: string; count: number }) => `${path} (${count} edits)`,
            readingFile: ({ file }: { file: string }) => `Reading ${file}`,
            writingFile: ({ file }: { file: string }) => `Writing ${file}`,
            modifyingFile: ({ file }: { file: string }) => `Modifying ${file}`,
            modifyingFiles: ({ count }: { count: number }) => `Modifying ${count} files`,
            modifyingMultipleFiles: ({ file, count }: { file: string; count: number }) => `${file} and ${count} more`,
            showingDiff: 'Showing changes',
        }
    },

    sideChat: {
        panelTitle: 'Side chats',
        allFiles: 'All files',
        newChat: 'New side chat',
        startButton: 'Start side chat',
        creating: 'Creating…',
        unavailable: 'This session cannot be forked while its machine is offline or provider metadata is unavailable.',
        emptyTitle: 'No side chats yet',
        emptySubtitle: 'Start an isolated conversation that keeps the parent context without writing back into its transcript.',
        close: 'Close side chat',
        expand: 'Open side chat full screen',
        defaultTitle: ({ index }: { index: number }) => `Side chat ${index}`,
    },

    files: {
        addPanel: 'Add workbench panel',
        changes: 'Changes',
        loadFailed: 'Could not load changes. Check your connection and try again.',
        fileLoadFailed: 'Could not load this file. Check your connection and try again.',
        searchFailed: 'Could not search files. Try again.',
        searchPlaceholder: 'Search files...',
        searchPlaceholderCompact: 'Search',
        detachedHead: 'detached HEAD',
        summary: ({ staged, unstaged }: { staged: number; unstaged: number }) => `${staged} staged • ${unstaged} unstaged`,
        branchDetails: 'Branch Details',
        gitGraph: 'Git Graph',
        allChanges: 'All',
        stagedTab: 'Staged',
        unstagedTab: 'Unstaged',
        notRepo: 'Not a git repository',
        notUnderGit: 'This directory is not under git version control',
        searching: 'Searching files...',
        noFilesFound: 'No files found',
        noFilesInProject: 'No files in project',
        tryDifferentTerm: 'Try a different search term',
        searchResults: ({ count }: { count: number }) => `Search Results (${count})`,
        projectRoot: 'Project root',
        stagedChanges: ({ count }: { count: number }) => `Staged Changes (${count})`,
        unstagedChanges: ({ count }: { count: number }) => `Unstaged Changes (${count})`,
        // File viewer strings
        loadingFile: ({ fileName }: { fileName: string }) => `Loading ${fileName}...`,
        binaryFile: 'Binary File',
        cannotDisplayBinary: 'Cannot display binary file content',
        diff: 'Diff',
        file: 'File',
        source: 'Source',
        preview: 'Preview',
        fileEmpty: 'File is empty',
        noChanges: 'No changes to display',
        fileTruncated: ({ loaded, total }: { loaded: string; total: string }) => `Showing ${loaded} of ${total}`,
        largeFileTitle: 'Large file',
        largeFileMessage: ({ fileName, size }: { fileName: string; size: string }) => `${fileName} is about ${size}. Loading the full file may take a while.`,
        largeFileConfirm: 'Load full file',
        largeFileCancel: 'Not now',
        largeFileSkipped: 'File not loaded',
        largeFileSkippedHint: 'This file is larger than 2 MB. Confirm loading it to preview the full content.',
        noChangesTitle: 'No changes',
        noChangesSubtitle: 'Working tree is clean',
        deleted: 'Deleted',
        modified: 'Modified',
        added: 'Added',
        renamed: 'Renamed',
        untracked: 'Untracked',
        showExplorer: 'Show file browser',
        hideExplorer: 'Hide file browser',
    },

    gitActions: {
        // Discard
        discard: 'Discard',
        discardFile: ({ fileName }: { fileName: string }) =>
            `Discard changes to ${fileName}? This cannot be undone.`,
        discardFileConfirm: 'Discard',
        discardAll: 'Discard All',
        discardAllMessage: 'This will revert all changes and remove untracked files. This cannot be undone.',
        // Stage / Unstage
        stage: 'Stage',
        unstage: 'Unstage',
        // Commit
        commit: 'Commit',
        commitTitle: 'Commit Changes',
        commitMessage: 'Enter a commit message:',
        commitPlaceholder: 'Describe your changes...',
        commitEmptyMessage: 'Commit message cannot be empty',
        // Push / Pull
        push: 'Push',
        pushTitle: 'Push Changes',
        pushMessage: 'Push local commits to the remote repository?',
        pull: 'Pull',
        pullTitle: 'Pull Changes',
        pullMessage: 'Pull latest changes from the remote repository?',
        // Stash
        stash: 'Stash',
        stashTitle: 'Stash Changes',
        stashMessage: 'Enter a stash message (optional):',
        stashPlaceholder: 'Stash message...',
        stashPop: 'Pop Stash',
        stashPopTitle: 'Pop Stash?',
        stashPopMessage: 'Apply the latest stash entry and remove it from the stash list?',
        stashDrop: 'Drop Stash',
        // Git Log
        gitLog: 'Git Log',
        commitDetails: 'Commit details',
        hash: 'Hash',
        parents: 'Parents',
        refs: 'Refs',
        openCommitDetails: ({ subject, hash }: { subject: string; hash: string }) => `Open commit details for ${subject}, ${hash}`,
        gitLogEmpty: 'No commits yet',
        gitGraphEmpty: 'No branch graph available',
        // Success messages
        discarded: 'Changes discarded',
        committed: 'Committed successfully',
        pushed: 'Pushed successfully',
        pulled: 'Pulled successfully',
        stashed: 'Changes stashed',
        stashPopped: 'Stash applied',
        staged: 'File staged',
        unstaged: 'File unstaged',
        // Ahead / behind
        ahead: ({ count }: { count: number }) => `↑${count}`,
        behind: ({ count }: { count: number }) => `↓${count}`,
    },

    settingsAccount: {
        // Account settings screen
        accountInformation: 'Account Information',
        status: 'Status',
        statusActive: 'Active',
        statusNotAuthenticated: 'Not Authenticated',
        anonymousId: 'Anonymous ID',
        publicId: 'Public ID',
        notAvailable: 'Not available',
        linkNewDevice: 'Link New Device',
        linkNewDeviceSubtitle: 'Scan QR code to link device',
        profile: 'Profile',
        name: 'Name',
        github: 'GitHub',
        tapToDisconnect: 'Tap to disconnect',
        server: 'Server',
        backup: 'Backup',
        backupDescription: 'Your secret key is the only way to recover your account. Save it in a secure place like a password manager.',
        secretKey: 'Secret Key',
        tapToReveal: 'Tap to reveal',
        tapToHide: 'Tap to hide',
        secretKeyLabel: 'SECRET KEY (TAP TO COPY)',
        secretKeyCopied: 'Secret key copied to clipboard. Store it in a safe place!',
        secretKeyCopiedTemporarily: 'Recovery key copied. It will be cleared from the clipboard after 30 seconds.',
        secretKeyMobileOnly: 'For security, recovery keys can only be revealed or copied in the iOS or Android app.',
        secretKeyDeviceAuthRequired: 'Set up Face ID, fingerprint, or device authentication before accessing the recovery key.',
        secretKeyAuthenticate: 'Authenticate to access recovery key',
        secretKeyAuthFailed: 'Device authentication failed. The recovery key remains hidden.',
        secretKeyCopyFailed: 'Failed to copy secret key',
        privacy: 'Privacy',
        privacyDescription: 'Help improve the app by sharing anonymous usage data. No personal information is collected.',
        analytics: 'Analytics',
        analyticsDisabled: 'No data is shared',
        analyticsEnabled: 'Anonymous usage data is shared',
        dangerZone: 'Danger Zone',
        logout: 'Logout',
        logoutSubtitle: 'Sign out and clear local data',
        logoutConfirm: 'Are you sure you want to logout? Make sure you have backed up your secret key!',

        // Push Notifications
        pushNotifications: 'Push Notifications',
        pushNotificationsFooter: 'Shows every push token registered on your account. Tap an old token to delete it.',
        pushPermission: 'Permission',
        pushPermLoading: 'Loading',
        pushPermUnavailable: 'Unavailable',
        pushPermAllowed: 'Allowed',
        pushPermDenied: 'Denied',
        pushPermNotRequested: 'Not requested',
        pushPermSubChecking: 'Checking push notification permissions for this device.',
        pushPermSubUnsupported: 'Push notification permissions are only managed on mobile devices.',
        pushPermSubGranted: 'This device can receive push notifications.',
        pushPermSubCanAskAgain: 'The system prompt can still be shown again from the app.',
        pushPermSubIOSDenied: 'The system will not show the permission prompt again. Open system settings to enable notifications.',
        pushRequestPermission: 'Request Permission Again',
        pushRequestPermSubtitleUnsupported: 'Push notification permissions are only available on iPhone and Android.',
        pushRequestPermSubtitleCanAsk: 'Shows the system permission prompt again.',
        pushRequestPermSubtitleCannotAsk: 'Opens system settings when the permission prompt is no longer available.',
        pushReregisterDevice: 'Re-register This Device',
        pushReregisterSubtitle: 'Fetches the current Expo token and registers it again.',
        pushCurrentToken: ({ token }: { token: string }) => `Current token ${token}`,
        pushTokensTitle: ({ count }: { count: number }) => `Registered Tokens (${count})`,
        pushTokensFooter: 'Current-device metadata comes from this phone. Older tokens use their token fingerprint plus server timestamps.',
        pushNoTokens: 'No registered push tokens',
        pushNoTokensSubtitle: 'Once this device is registered, it will appear here.',
        pushThisDevice: 'This device',
        pushOtherDevice: 'Other device or stale registration',
        pushRegistered: ({ time }: { time: string }) => `Registered: ${time}`,
        pushLastSeen: ({ time }: { time: string }) => `Last seen: ${time}`,
        pushServerId: ({ id }: { id: string }) => `Server ID: ${id}`,
        pushTokenLabel: ({ token }: { token: string }) => `Token: ${token}`,
        pushSuccessEnabled: 'Push notifications are enabled for this device.',
        pushOpenSettings: 'Open Settings',
        pushOpenedSettingsMsg: 'The system will not show the permission prompt again, so AgentHub opened Settings instead.',
        pushPermNotGranted: 'Push notification permission was not granted.',
        pushNotEnabledYet: 'Push notifications are not enabled for this device yet.',
        pushTokenRefreshed: 'This device push token was refreshed.',
        pushDeleteToken: 'Delete Push Token',
        pushDeleteTokenConfirm: ({ token }: { token: string }) => `Remove ${token} from your account?`,
        pushErrorLoadSettings: 'Failed to load push notification settings.',
        pushErrorRequestPerm: 'Failed to request push notification permission.',
        pushErrorRefresh: 'Failed to refresh this device push token.',
        pushErrorDelete: 'Failed to delete push token.',
    },

    settingsLanguage: {
        // Language settings screen
        title: 'Language',
        description: 'Choose your preferred language for the app interface. This will sync across all your devices.',
        currentLanguage: 'Current Language',
        automatic: 'Automatic',
        automaticSubtitle: 'Detect from device settings',
        needsRestart: 'Language Changed',
        needsRestartMessage: 'The app needs to restart to apply the new language setting.',
        restartNow: 'Restart Now',
    },

    connectButton: {
        authenticate: 'Authenticate Terminal',
        authenticateWithUrlPaste: 'Authenticate Terminal with URL paste',
        pasteAuthUrl: 'Paste the auth URL from your terminal',
    },

    updateBanner: {
        updateAvailable: 'Update available',
        pressToApply: 'Press to apply the update',
        checkingForUpdate: 'Checking for updates...',
        checkingForUpdateSubtitle: 'This only takes a moment',
        downloadingUpdate: 'Downloading update...',
        downloadingUpdateSubtitle: 'The new version is being prepared',
        updateReady: 'New version is ready',
        restartToApply: 'Tap to restart the app',
        whatsNew: "What's new",
        seeLatest: 'See the latest updates and improvements',
        nativeUpdateAvailable: 'App Update Available',
        tapToUpdateAppStore: 'Tap to update in App Store',
        tapToUpdatePlayStore: 'Tap to update in Play Store',
    },

    changelog: {
        // Used by the changelog screen
        version: ({ version }: { version: number }) => `Version ${version}`,
        noEntriesAvailable: 'No changelog entries available.',
        loadError: 'Could not load the changelog.',
        versionCount: ({ count }: { count: number }) => count === 1 ? '1 version' : `${count} versions`,
        changeCount: ({ count }: { count: number }) => count === 1 ? '1 update' : `${count} updates`,
        latestVersion: ({ version }: { version: number }) => `Latest ${version}`,
    },

    terminal: {
        // Used by terminal connection screens
        webBrowserRequired: 'Web Browser Required',
        webBrowserRequiredDescription: 'Terminal connection links can only be opened in a web browser for security reasons. Please use the QR code scanner or open this link on a computer.',
        processingConnection: 'Processing connection...',
        invalidConnectionLink: 'Invalid Connection Link',
        invalidConnectionLinkDescription: 'The connection link is missing or invalid. Please check the URL and try again.',
        connectTerminal: 'Connect Terminal',
        terminalRequestDescription: 'A terminal is requesting to connect to your AgentHub account. This will allow the terminal to send and receive messages securely.',
        connectionDetails: 'Connection Details',
        publicKey: 'Public Key',
        encryption: 'Encryption',
        endToEndEncrypted: 'End-to-end encrypted',
        acceptConnection: 'Accept Connection',
        connecting: 'Connecting...',
        reject: 'Reject',
        security: 'Security',
        securityFooter: 'This connection link was processed securely in your browser and was never sent to any server. Your private data will remain secure and only you can decrypt the messages.',
        securityFooterDevice: 'This connection was processed securely on your device and was never sent to any server. Your private data will remain secure and only you can decrypt the messages.',
        clientSideProcessing: 'Client-Side Processing',
        linkProcessedLocally: 'Link processed locally in browser',
        linkProcessedOnDevice: 'Link processed locally on device',
    },

    modals: {
        // Used across connect flows and settings
        authenticateTerminal: 'Authenticate Terminal',
        pasteUrlFromTerminal: 'Paste the authentication link shown on your computer to finish connecting this device.',
        deviceLinkedSuccessfully: 'Device linked successfully',
        terminalConnectedSuccessfully: 'Terminal connected successfully',
        invalidAuthUrl: 'Invalid authentication URL',
        developerMode: 'Developer Mode',
        developerModeEnabled: 'Developer mode enabled',
        developerModeDisabled: 'Developer mode disabled',
        disconnectGithub: 'Disconnect GitHub',
        disconnectGithubConfirm: 'Are you sure you want to disconnect your GitHub account?',
        disconnectService: ({ service }: { service: string }) => 
            `Disconnect ${service}`,
        disconnectServiceConfirm: ({ service }: { service: string }) => 
            `Are you sure you want to disconnect ${service} from your account?`,
        disconnect: 'Disconnect',
        failedToConnectTerminal: 'Failed to connect terminal',
        cameraPermissionsRequiredToConnectTerminal: 'Camera permissions are required to connect terminal',
        failedToLinkDevice: 'Failed to link device',
        cameraPermissionsRequiredToScanQr: 'Camera permissions are required to scan QR codes'
    },

    navigation: {
        // Navigation titles and screen headers
        connectTerminal: 'Connect Terminal',
        linkNewDevice: 'Link New Device', 
        restoreWithSecretKey: 'Restore with Secret Key',
        whatsNew: "What's New",
    },

    welcome: {
        // Main welcome screen for unauthenticated users
        title: 'Codex and Claude Code mobile client',
        subtitle: 'End-to-end encrypted and your account is stored only on your device.',
        createAccount: 'Create account',
        linkOrRestoreAccount: 'Link or restore account',
        loginWithMobileApp: 'Login with mobile app',
    },

    review: {
        // Used by utils/requestReview.ts
        enjoyingApp: 'Enjoying the app?',
        feedbackPrompt: "We'd love to hear your feedback!",
        yesILoveIt: 'Yes, I love it!',
        notReally: 'Not really'
    },

    items: {
        // Used by Item component for copy toast
        copiedToClipboard: ({ label }: { label: string }) => `${label} copied to clipboard`
    },

    machine: {
        notFound: 'Machine not found',
        launchNewSessionInDirectory: 'Launch New Session in Directory',
        statusAndProperties: 'Status & Properties',
        systemResources: 'System resources',
        memory: 'Memory',
        network: 'Network',
        downloadSpeed: 'Download',
        uploadSpeed: 'Upload',
        storage: 'Storage',
        used: 'Used',
        available: 'Available',
        metricsUnavailable: 'Live metrics unavailable',
        metricsStale: 'Showing the last available snapshot',
        actions: 'Actions',
        startSessionOnThisMachine: 'Start Session on This Machine',
        startSessionOnThisMachineSubtitle: 'Open the new session screen with this machine selected.',
        startSessionOfflineSubtitle: 'Bring this machine online before starting a session.',
        offlineUnableToSpawn: 'Launcher disabled while machine is offline',
        offlineHelp: '• Make sure your computer is online\n• Run `agenthub daemon status` to diagnose\n• Are you running the latest CLI version? Upgrade with `npm install -g @artsum/agenthub@latest`',
        daemon: 'Daemon',
        status: 'Status',
        stopDaemon: 'Stop Daemon',
        lastKnownPid: 'Last Known PID',
        lastKnownHttpPort: 'Last Known HTTP Port',
        startedAt: 'Started At',
        cliVersion: 'CLI Version',
        daemonStateVersion: 'Daemon State Version',
        activeSessions: ({ count }: { count: number }) => `Active Sessions (${count})`,
        machineGroup: 'Machine',
        host: 'Host',
        machineId: 'Machine ID',
        username: 'Username',
        homeDirectory: 'Home Directory',
        platform: 'Platform',
        architecture: 'Architecture',
        lastSeen: 'Last Seen',
        never: 'Never',
        metadataVersion: 'Metadata Version',
        cliAvailability: 'CLI Availability',
        cliInstalled: 'Installed',
        cliNotFound: 'Not found',
        lastDetected: 'Last Detected',
        untitledSession: 'Untitled Session',
        back: 'Back',
        dangerZone: 'Danger Zone',
        delete: 'Delete Machine',
        deleteFooter: 'Remove this machine from your account. Session history will be preserved, but you will not be able to start new sessions on this machine.',
        deleteConfirmTitle: 'Delete this machine?',
        deleteConfirmMessage: 'The machine will be removed from your account. Session history will be preserved, but you will not be able to start new sessions until you reconnect the daemon.',
        deleteFailed: 'Failed to delete machine.',
        stopDaemonTitle: 'Stop Daemon?',
        stopDaemonMessage: 'You will not be able to spawn new sessions on this machine until you restart the daemon on your computer again. Your current sessions will stay alive.',
        daemonStopped: 'Daemon Stopped',
        stopDaemonFailed: 'Failed to stop daemon. It may not be running.',
        renameTitle: 'Rename Machine',
        renameMessage: 'Give this machine a custom name. Leave empty to use the default hostname.',
        renamePlaceholder: 'Enter machine name',
        renameSuccess: 'Machine renamed successfully',
        renameFailed: 'Failed to rename machine',
        previousSessions: 'Previous Sessions (up to 5 most recent)',
    },

    machines: {
        noDevices: 'No Devices',
        noDevicesSubtitle: 'Connect a computer by running AgentHub CLI on it.',
        ungrouped: 'Ungrouped',
        newGroup: 'New Group',
        enterGroupName: 'Enter a group name',
        noUngroupedDevices: 'No ungrouped devices are available. Long-press a device to move it between groups.',
        groupName: 'Group name',
        renameGroup: 'Rename Group',
        deleteGroup: 'Delete Group',
        deleteGroupConfirm: ({ name }: { name: string }) => `Remove the group "${name}"? Devices will be moved to Ungrouped.`,
        moveToGroup: 'Move to Group',
        groupAlreadyExists: 'A group with this name already exists.',
        emptyGroup: 'Empty Group',
        emptyGroupSubtitle: "Use a device\'s more menu to move it here.",
        groupActions: 'Group Actions',
        deviceActions: 'Device Actions',
        openDetails: 'Open Details',
        pinToTop: 'Pin to Top',
        moveUp: 'Move Up',
        moveDown: 'Move Down',
    },

    message: {
        loading: 'Loading message...',
        notFound: 'Message not found',
        switchedToMode: ({ mode }: { mode: string }) => `Switched to ${mode} mode`,
        unknownEvent: 'Unknown event',
        usageLimitUntil: ({ time }: { time: string }) => `Usage limit reached until ${time}`,
        sentAsGoal: 'Sent as goal',
        unknownTime: 'unknown time',
    },

    codex: {
        // Codex permission dialog buttons
        permissions: {
            yesForSession: "Yes, and don't ask for a session",
            stopAndExplain: 'Stop, and explain what to do',
        }
    },

    claude: {
        // Claude permission dialog buttons
        permissions: {
            yesAllowAllEdits: 'Yes, allow all edits during this session',
            yesAllowEverything: 'Yes, allow everything during this session',
            yesForTool: "Yes, don't ask again for this tool",
            noTellClaude: 'No, and provide feedback',
        }
    },

    textSelection: {
        // Text selection screen
        selectText: 'Select text range',
        title: 'Select Text',
        noTextProvided: 'No text provided',
        textNotFound: 'Text not found or expired',
        textCopied: 'Text copied to clipboard',
        failedToCopy: 'Failed to copy text to clipboard',
        noTextToCopy: 'No text available to copy',
        share: 'Share selected text',
        shareTitle: 'Selected text',
        failedToShare: 'Failed to open the share sheet',
        noTextToShare: 'No text available to share',
    },

    externalShares: {
        title: 'Shared links',
        settingsSubtitle: 'Manage encrypted, expiring links',
        createSecureLink: 'Create secure link',
        chooseExpiry: 'Choose how long this encrypted link should work',
        oneHour: '1 hour',
        oneDay: '24 hours',
        sevenDays: '7 days',
        creating: 'Creating secure link…',
        unavailable: 'Secure links are unavailable',
        unavailableDescription: 'A trusted HTTPS share origin must be configured first.',
        createFailed: 'Could not create the secure link. Try again.',
        linkCopied: 'The secure link was copied to the clipboard.',
        linkReadyCopyFailed: 'The link was created, but this device could not share or copy it. Revoke it from Shared links and try again.',
        empty: 'No shared links yet',
        active: 'Active',
        expired: 'Expired',
        revoked: 'Revoked',
        expires: 'Expires',
        revoke: 'Revoke link',
        revokeConfirm: 'Anyone with this link will immediately lose access.',
        revokeFailed: 'Could not revoke this link. Try again.',
        loadFailed: 'Could not load shared links.',
        publicTitle: 'Encrypted shared text',
        loading: 'Opening encrypted share…',
        notFound: 'This shared link is unavailable, expired, or revoked.',
        missingKey: 'This link is missing its decryption key. Open the original shared link again.',
        invalidKey: 'This link could not be decrypted. Check that the complete link was copied.',
    },


    markdown: {
        // Markdown copy functionality
        codeCopied: 'Code copied',
        copyFailed: 'Copy failed',
        mermaidRenderFailed: 'Failed to render mermaid diagram',
    },

    artifacts: {
        // Artifacts feature
        title: 'Artifacts',
        countSingular: '1 artifact',
        countPlural: ({ count }: { count: number }) => `${count} artifacts`,
        empty: 'No artifacts yet',
        emptyDescription: 'Create your first artifact to get started',
        new: 'New Artifact',
        edit: 'Edit Artifact',
        delete: 'Delete',
        untitled: 'Untitled artifact',
        noContent: 'No content',
        deleteError: 'Failed to delete artifact. Please try again.',
        updateError: 'Failed to update artifact. Please try again.',
        notFound: 'Artifact not found',
        discardChanges: 'Discard changes?',
        discardChangesDescription: 'You have unsaved changes. Are you sure you want to discard them?',
        deleteConfirm: 'Delete artifact?',
        deleteConfirmDescription: 'This action cannot be undone',
        titleLabel: 'TITLE',
        titlePlaceholder: 'Enter a title for your artifact',
        bodyLabel: 'CONTENT',
        bodyPlaceholder: 'Write your content here...',
        emptyFieldsError: 'Please enter a title or content',
        createError: 'Failed to create artifact. Please try again.',
        save: 'Save',
        saving: 'Saving...',
        loading: 'Loading artifacts...',
        error: 'Failed to load artifact',
    },

    usage: {
        // Usage panel strings
        today: 'Today',
        last7Days: 'Last 7 days',
        last30Days: 'Last 30 days',
        tokens: 'Tokens',
        usageOverTime: 'Usage over time',
        byModel: 'By Model',
        noData: 'No usage data available',
        notAuthenticated: 'Not authenticated',
        loadFailed: 'Failed to load usage data',
        period: 'Period',
        agentScope: 'Agent scope',
        agentAll: 'All',
        agentUnknown: 'Unknown agent',
        periodTokens: 'Period tokens',
        activeBucketsHint: ({ count }: { count: number }) => `${count} active buckets`,
        activeReports: 'Usage records',
        avgPerReport: ({ tokens }: { tokens: string }) => `${tokens} avg / record`,
        peakBucket: 'Peak bucket',
        cacheReuse: 'Cache reuse',
        tokenMix: 'Token mix',
        tokenMixSubtitle: ({ total }: { total: string }) => `${total} tokens by type`,
        trendSubtitle: ({ buckets, active }: { buckets: number; active: number }) => `${active} active of ${buckets} buckets`,
        axisTokens: 'Y axis: tokens',
        axisTime: 'X axis: time',
        bucketDetail: ({ reports, input, output }: { reports: number; input: string; output: string }) => `${reports} records · input ${input} · output ${output}`,
        modelGuideButton: 'Show model usage guide',
        modelSubtitle: ({ count }: { count: number }) => `${count} ranked models`,
        modelGuide: 'Each row is one recorded model under an agent. The percentage is its share of the selected range; the colored strip shows that model’s input, cache, output, and reasoning token mix.',
        noModelData: 'No model dimension recorded yet',
        unrecordedModel: 'Unrecorded model',
        modelShare: ({ share }: { share: string }) => `${share} of period`,
        modelRecords: ({ count }: { count: number }) => `${count} records`,
        modelAverage: ({ tokens }: { tokens: string }) => `${tokens} avg`,
        metricTotal: 'Total',
        metricInput: 'Input',
        metricOutput: 'Output',
        metricCacheCreation: 'Cache write',
        metricCacheRead: 'Cache read',
        metricReasoning: 'Reasoning',
        metricOther: 'Other',
    },

    devTools: {
        // App Information
        appInfo: 'App Information',
        version: 'Version',
        buildNumber: 'Build Number',
        sdkVersion: 'SDK Version',
        platform: 'Platform',
        anonymousId: 'Anonymous ID',

        // Debug Options
        debugOptions: 'Debug Options',
        debugMode: 'Debug Mode',
        consoleOutput: 'Console Output',
        consoleOutputSubtitle: 'Enable console output in production builds',
        verboseLogging: 'Verbose Logging',
        verboseLoggingSubtitle: 'Log all network requests and responses',
        viewLogs: 'View Logs',

        // Component Demos
        componentDemos: 'Component Demos',
        deviceInfo: 'Device Info',
        deviceInfoSubtitle: 'Safe area insets and device parameters',
        listComponents: 'List Components',
        listComponentsSubtitle: 'Demo of Item, ItemGroup, and ItemList',
        typography: 'Typography',
        typographySubtitle: 'All typography styles',
        colors: 'Colors',
        colorsSubtitle: 'Color palette and themes',
        messageDemos: 'Message Demos',
        messageDemosSubtitle: 'Various message types and components',
        invertedList: 'Inverted List Test',
        invertedListSubtitle: 'Test inverted FlatList with keyboard',
        toolViews: 'Tool Views',
        toolViewsSubtitle: 'Tool call visualization components',
        shimmerView: 'Shimmer View',
        shimmerViewSubtitle: 'Shimmer loading effects with masks',
        multiTextInput: 'Multi Text Input',
        multiTextInputSubtitle: 'Auto-growing multiline text input',
        inputStyles: 'Input Styles',
        inputStylesSubtitle: '10+ different input field style variants',
        modalSystem: 'Modal System',
        modalSystemSubtitle: 'Alert, confirm, and custom modals',
        unitTests: 'Unit Tests',
        unitTestsSubtitle: 'Run tests in the app environment',
        unistylesDemo: 'Unistyles Demo',
        unistylesDemoSubtitle: 'React Native Unistyles features and capabilities',
        qrCodeTest: 'QR Code Test',
        qrCodeTestSubtitle: 'Test QR code generation with different parameters',
        sessionComposer: 'Session Composer',
        sessionComposerSubtitle: 'New session creation screen layout',

        // Test Features
        testFeatures: 'Test Features',
        testFeaturesFooter: 'These actions may affect app stability',
        claudeOAuthTest: 'Claude OAuth Test',
        claudeOAuthSubtitle: 'Test Claude authentication flow',
        testCrash: 'Test Crash',
        testCrashSubtitle: 'Trigger a test crash',
        testCrashConfirm: 'This will crash the app. Continue?',
        clearCacheTitle: 'Clear Cache',
        clearCacheSubtitle: 'Remove all cached data',
        clearCacheConfirm: 'Are you sure you want to clear all cached data?',
        clearCacheDone: 'Cache has been cleared',
        resetChangelogTitle: 'Reset Changelog',
        resetChangelogSubtitle: "Show 'What's New' banner again",
        resetChangelogDone: 'Changelog reset. Restart app to see the banner.',
        resetAppTitle: 'Reset App State',
        resetAppSubtitle: 'Clear all user data and preferences',
        resetAppConfirm: 'This will delete all data. Are you sure?',

        // System
        system: 'System',
        purchases: 'Purchases',
        purchasesSubtitle: 'View subscriptions and entitlements',
        expoConstants: 'Expo Constants',
        expoConstantsSubtitle: 'View expoConfig, manifests, and system constants',

        // Network
        network: 'Network',
        apiEndpoint: 'API Endpoint',
        logServer: 'Log Server',
        logServerSubtitle: 'Sends unencrypted console logs over HTTP',
        socketIoStatus: 'Socket.IO Status',
        connectingToServer: 'Connecting to server...',
        noConnectionInfo: 'No connection info',
        connected: ({ time }: { time: string }) => `Connected ${time}`,
        lastConnected: ({ time }: { time: string }) => `Last connected ${time}`,

        // Modal strings
        editApiEndpoint: 'Edit API Endpoint',
        enterServerUrl: 'Enter the server URL:',
        serverUrlUpdated: 'Server URL updated. Please restart the app for changes to take effect.',
        invalidUrl: 'Invalid URL',
        enterValidUrl: 'Please enter a valid URL',
        remoteLogServer: 'Remote Log Server',
        remoteLogDescription: "Sends ALL console output as unencrypted plaintext over HTTP to this URL. Use your Mac's local IP (e.g. http://192.168.1.5:8787). Run \"yarn app-logs\" on your Mac to receive. Clear to disable.",
        remoteLoggingDisabled: 'Remote logging disabled. Restart app for changes to take effect.',
        logServerUpdated: 'Log server URL updated. Restart app for changes to take effect.',
        off: 'Off',
        justNow: 'Just now',
        timeAgo: ({ value, unit }: { value: number; unit: string }) => `${value}${unit} ago`,
    },

    fileBrowser: {
        title: 'File browser',
        browseOnline: 'Browse, preview, and download files from the host root.',
        browseOffline: 'Remote files become available when the device is online.',
        noTransfers: 'No transfers yet',
        noTransfersSubtitle: 'Remote downloads from the file browser will appear here.',
        viewAllTransfers: 'View all transfers',
        transferSummary: ({ active, failed, paused }: { active: number; failed: number; paused: number }) => `${active} active · ${failed} failed · ${paused} paused`,
        failedTasks: 'Failed tasks',
        downloadingTasks: 'Downloading',
        pausedTasks: 'Paused tasks',
        viewDownloadTask: 'View download task',
        pauseDownload: 'Pause download',
        resumeDownload: 'Resume download',
        cancelDownload: 'Cancel download',
        downloadToDevice: 'Download to this device',
        queuedTitle: 'Added to transfers',
        view: 'View',
        fileInfoTitle: 'File information',
        unknown: 'Unknown',
        fileInfoMessage: ({ name, path, size, modified }: { name: string; path: string; size: string; modified: string }) => `Name: ${name}\nPath: ${path}\nSize: ${size}\nModified: ${modified}`,
        copyPath: 'Copy path',
        deleteRemoteFile: 'Delete remote file',
        deleteTitle: 'Delete remote file?',
        deleteMessage: ({ path }: { path: string }) => `This file will be deleted from the device:\n${path}\n\nThis action cannot be undone.`,
        deleteFailed: 'Failed to delete the remote file.',
        deviceOffline: 'Device offline',
        deviceOfflineMessage: 'The remote AgentHub daemon must be online to browse files.',
        loadingDevice: 'Loading device information',
        selectFile: 'Select a file to preview its contents',
        missingReadSource: 'No file-reading source is available.',
        missingMachineForDownload: 'This session has no device information, so the download cannot start.',
        unknownError: 'Unknown error',
    },

    transferManager: {
        title: 'File transfers',
        machineTitle: ({ machine }: { machine: string }) => `${machine} · File transfers`,
        management: 'File transfer management',
        devices: 'Devices',
        currentDevice: 'Current device',
        allDevices: 'All devices',
        filterAll: 'All',
        filterActive: 'Active',
        filterFailed: 'Failed',
        filterPaused: 'Paused',
        filterCompleted: 'Completed',
        statusQueued: 'Queued',
        statusDownloading: 'Downloading',
        statusPaused: 'Paused',
        statusCompleted: 'Completed',
        statusFailed: 'Failed',
        statusCancelled: 'Cancelled',
        streamRetry: ({ attempt, total }: { attempt: number; total: number }) => `Connection interrupted. Retrying ${attempt}/${total}`,
        systemAuthorizedDirectory: 'System-authorized directory',
        appPrivateDirectory: 'App-private download directory',
        setupDirectoryTitle: 'Set download directory',
        setupDirectoryMessage: 'No system-authorized download directory is configured. Downloading now saves to the app-private directory, which Android file managers usually cannot open. Choose a default download directory first.',
        setupDirectoryCancel: 'Not now',
        setupDirectoryConfirm: 'Choose directory',
        notCompleted: 'Not completed',
        authorizedDirectory: 'System-authorized directory',
        noFileHandler: 'No app on this device can open this file.',
        fileNotDownloaded: 'The file has not finished downloading.',
        cannotOpenFile: 'Unable to open file',
        unknownError: 'Unknown error',
        directoryUnavailable: 'The directory is not available yet.',
        cannotOpenDirectory: 'Unable to open directory',
        privateDirectoryUnsupported: 'Android file managers usually cannot browse the app-private download directory. Open the downloaded file directly, or choose a system-authorized directory from the top-right menu before downloading.',
        noDirectoryHandler: 'No file manager on this device can open the directory.',
        pauseDownload: 'Pause download',
        resumeDownload: 'Resume download',
        openFile: 'Open file',
        cancelDownload: 'Cancel download',
        removeTransfer: 'Remove transfer',
        deleteRecordAndFile: 'Delete record and file',
        deleteRecord: 'Delete record',
        removeTitle: 'Delete transfer record?',
        removeDescription: 'This removes the transfer record from the list.',
        deleteLocalFile: 'Also delete the local file',
        deleteLocalFileHint: 'This choice is remembered for next time. Deleting the file cannot be undone.',
        noLocalFile: 'This task does not have a completed local file to delete.',
        detailTitle: 'Transfer details',
        file: 'File',
        status: 'Status',
        device: 'Device',
        remotePath: 'Remote path',
        localPath: 'Local path',
        progress: 'Progress',
        error: 'Error',
        createdAt: 'Created',
        updatedAt: 'Updated',
        openDirectory: 'Open directory',
        close: 'Close',
        authorizedDirectoryDescription: 'This is an Android system-authorized directory. Completed downloads will be saved here.',
        privateDirectoryDescription: 'The app-private download directory is used by default and needs no extra storage permission. You can choose a system-authorized directory from this menu.',
        defaultLocation: 'Default download location',
        unavailableLocalDirectory: 'This platform does not provide a local file directory.',
        unsupportedDirectoryTitle: 'Choosing a download directory is not supported on this platform',
        unsupportedDirectoryMessage: 'The app-private download directory will be used.',
        locationUpdated: 'Default download location updated',
        locationUpdatedMessage: ({ label }: { label: string }) => `${label}\nCompleted downloads will be saved to this system-authorized directory.`,
        cannotSetDirectory: 'Unable to set download directory',
        restorePrivateTitle: 'Restore the app-private download directory?',
        restorePrivateMessage: 'Future downloads will be saved in the app-private directory. Existing downloaded files will not be moved.',
        restore: 'Restore',
        nothingToClear: 'There are no completed tasks to clear.',
        clearCompletedTitle: 'Clear completed tasks?',
        clearCompletedMessage: ({ count }: { count: number }) => `Remove ${count} completed transfer record${count === 1 ? '' : 's'} from this list? Downloaded files will not be deleted.`,
        clear: 'Clear',
        deleteLocalFailed: 'Failed to delete the local file',
        showDefaultLocation: 'Location',
        openDefaultLocation: 'Open folder',
        chooseDefaultLocation: 'Choose folder',
        chooseDefaultLocationAndroid: 'Choose (Android)',
        restorePrivateDirectory: 'Private folder',
        clearCompleted: 'Clear completed',
        clearCompletedCount: ({ count }: { count: number }) => `Clear completed (${count})`,
        noTasks: 'No transfer tasks',
        noTasksSubtitle: 'Remote downloads from the file browser will appear here.',
        cancelDownloadTitle: 'Cancel download?',
        keepDownload: 'Keep download',
    },


    directoryTree: {
        title: 'Explorer',
        loadFailed: 'Could not load files. Check your connection and try again.',
        searchPlaceholder: 'Search files...',
        loading: 'Loading...',
        emptyDirectory: 'Empty directory',
        binaryFile: 'Binary file',
        binaryFileHint: 'Cannot preview binary files',
        loadingFile: 'Loading file...',
        noFilesFound: 'No files found',
        backToTree: 'Back',
        rootLabel: 'Project root',
        fileTruncated: ({ loaded, total }: { loaded: string; total: string }) => `File is too large, showing ${loaded} of ${total}`,
    },

    fileReferencePicker: {
        title: 'Select Files & Folders',
        searchPlaceholder: 'Search files...',
        done: 'Done',
        selectedCount: ({ count }: { count: number }) =>
            count === 0 ? 'Done' : `Done (${count})`,
        emptyState: 'No files found',
        loading: 'Loading files...',
    },

    attachmentMenu: {
        projectFiles: 'Reference project files',
        localFiles: 'Reference local files',
    },

} as const;

export type Translations = typeof en;

/**
 * Generic translation type that matches the structure of Translations
 * but allows different string values (for other languages)
 */
export type TranslationStructure = {
    readonly [K in keyof Translations]: LocalizedTranslationValue<Translations[K]>;
};

type LocalizedTranslationValue<T> = T extends string
    ? string
    : T extends (...args: any[]) => string
        ? T
        : T extends object
            ? { readonly [K in keyof T]: LocalizedTranslationValue<T[K]> }
            : T;
