import type { Session, Machine, GitStatus } from './storageTypes';
import type { GitStatusFiles } from './gitStatusFiles';
import type { NormalizedMessage } from './typesRaw';
import type { Settings } from './settings';
import type { LocalSettings } from './localSettings';
import type { Purchases } from './purchases';
import type { Profile } from './profile';
import type { DecryptedArtifact } from './artifactTypes';
import type { ProjectListViewItem, SessionListItem, SessionListViewItem } from './storageProjection';
import type { LatestSessionUsage } from './sessionUsage';
import type { OfficialCodexThread } from './officialThreads';
import type { FilePreviewCache } from './filePreviewCachePolicy';
import type { SessionMessageLoadError } from './sessionMessageLoadState';
import type { SessionMessages } from './storage';

export interface StorageState {
    settings: Settings;
    settingsVersion: number | null;
    localSettings: LocalSettings;
    purchases: Purchases;
    profile: Profile;
    sessions: Record<string, Session>;
    sessionsData: SessionListItem[] | null;
    sessionListViewData: SessionListViewItem[] | null;
    projectListViewData: ProjectListViewItem[] | null;
    officialCodexThreads: Record<string, OfficialCodexThread[]>;
    sessionLastViewedAt: Record<string, number>;
    sessionLastViewedState: Record<string, string>;
    sessionUnviewedCompletionAt: Record<string, number>;
    sessionMessages: Record<string, SessionMessages>;
    sessionGitStatus: Record<string, GitStatus | null>;
    sessionGitStatusFiles: Record<string, GitStatusFiles | null>;
    sessionFileCache: FilePreviewCache;
    machines: Record<string, Machine>;
    artifacts: Record<string, DecryptedArtifact>;
    socketStatus: 'disconnected' | 'connecting' | 'connected' | 'error';
    socketLastConnectedAt: number | null;
    socketLastDisconnectedAt: number | null;
    isDataReady: boolean;
    nativeUpdateStatus: { available: boolean; updateUrl?: string } | null;
    officialResumeSessions: Record<string, { threadId: string; startedAt: number; title?: string | null }>;
    resetAccountState: () => void;
    applySessions: (sessions: (Omit<Session, 'presence'> & { presence?: 'online' | number })[], replace?: boolean) => void;
    applyMachines: (machines: Machine[], replace?: boolean) => void;
    deleteMachine: (machineId: string) => void;
    applyLoaded: () => void;
    applyReady: () => void;
    applyMessages: (sessionId: string, messages: NormalizedMessage[]) => { changed: string[]; hasReadyEvent: boolean };
    applyMessagesLoaded: (sessionId: string) => void;
    applyMessagesLoadError: (sessionId: string, error: SessionMessageLoadError | null) => void;
    applyMessageHistoryState: (sessionId: string, state: Partial<Pick<SessionMessages, 'hasMoreBefore' | 'isLoadingBefore'>>) => void;
    applySettings: (settings: Settings, version: number) => void;
    applySettingsLocal: (settings: Partial<Settings>) => void;
    applyLocalSettings: (settings: Partial<LocalSettings>) => void;
    applyProfile: (profile: Profile) => void;
    applySessionUsage: (sessionId: string, usage: LatestSessionUsage) => void;
    applyGitStatus: (sessionId: string, status: GitStatus | null) => void;
    applyGitStatusFiles: (sessionId: string, files: GitStatusFiles | null) => void;
    applyFileCache: (sessionId: string, filePath: string, content: string | null, diff: string | null, isBinary: boolean, totalSize?: number, truncated?: boolean, version?: string) => void;
    touchFileCache: (sessionId: string, filePath: string) => void;
    applyNativeUpdateStatus: (status: { available: boolean; updateUrl?: string } | null) => void;
    isMutableToolCall: (sessionId: string, callId: string) => boolean;
    setSocketStatus: (status: 'disconnected' | 'connecting' | 'connected' | 'error') => void;
    getActiveSessions: () => Session[];
    updateSessionDraft: (sessionId: string, draft: string | null) => void;
    updateSessionPermissionMode: (sessionId: string, mode: string) => void;
    updateSessionModelMode: (sessionId: string, mode: string) => void;
    updateSessionEffortLevel: (sessionId: string, level: string) => void;
    markSessionViewed: (sessionId: string) => void;
    applyArtifacts: (artifacts: DecryptedArtifact[]) => void;
    addArtifact: (artifact: DecryptedArtifact) => void;
    updateArtifact: (artifact: DecryptedArtifact) => void;
    deleteArtifact: (artifactId: string) => void;
    deleteSession: (sessionId: string) => void;
    getProjects: () => import('./projectManager').Project[];
    getProject: (projectId: string) => import('./projectManager').Project | null;
    getProjectForSession: (sessionId: string) => import('./projectManager').Project | null;
    getProjectSessions: (projectId: string) => string[];
    getProjectGitStatus: (projectId: string) => GitStatus | null;
    getSessionProjectGitStatus: (sessionId: string) => GitStatus | null;
    updateSessionProjectGitStatus: (sessionId: string, status: GitStatus | null) => void;
    applyOfficialCodexThreads: (machineId: string, threads: OfficialCodexThread[]) => void;
    startOfficialResumeSession: (sessionId: string, threadId: string, title?: string | null) => void;
    clearOfficialResumeSession: (sessionId: string) => void;
}
