import { Platform } from 'react-native';
import { StyleSheet } from 'react-native-unistyles';
import { Typography } from '@/constants/Typography';
import { layout } from '@/components/layout';
import { MULTI_TEXT_INPUT_LINE_HEIGHT } from '@/components/MultiTextInput';

const MINIMUM_TAP_TARGET = 44;
const COMPOSER_SEND_BUTTON_SIZE = MINIMUM_TAP_TARGET;
const COMPOSER_INPUT_VERTICAL_PADDING = Platform.OS === 'web' ? 10 : 8;
const COMPOSER_SEND_BUTTON_MARGIN_BOTTOM = Math.max(
    0,
    Math.round((MULTI_TEXT_INPUT_LINE_HEIGHT + COMPOSER_INPUT_VERTICAL_PADDING * 2 - COMPOSER_SEND_BUTTON_SIZE) / 2),
);

export const styles = StyleSheet.create((theme) => ({
    container: {
        flex: 1,
        backgroundColor: theme.colors.canvas,
    },
    backgroundTexture: {
        position: 'absolute',
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
    },
    backgroundSheen: {
        position: 'absolute',
        width: '58%',
        height: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.56)',
        transform: [{ rotate: '-36deg' }],
    },
    inner: {
        flex: 1,
    },
    screenReaderHeading: {
        position: 'absolute',
        width: 1,
        height: 1,
        overflow: 'hidden',
        opacity: 0,
    },
    contentScroll: {
        flex: 1,
    },
    contentScrollContent: {
        paddingHorizontal: 12,
        paddingBottom: 18,
    },
    contentColumn: {
        maxWidth: layout.maxWidth,
        width: '100%',
        alignSelf: 'center',
        gap: 8,
    },
    inputDock: {
        maxWidth: layout.maxWidth,
        width: '100%',
        alignSelf: 'center',
        paddingHorizontal: 12,
        gap: 8,
    },
    configBox: {
        backgroundColor: theme.colors.glass.raised,
        borderWidth: 1,
        borderColor: theme.dark ? 'rgba(238, 248, 250, 0.18)' : theme.colors.glass.borderStrong,
        borderRadius: Platform.select({ default: 16, android: 20 }),
        paddingVertical: 10,
        paddingHorizontal: 10,
        overflow: 'hidden',
        shadowColor: theme.dark ? '#000' : theme.colors.glass.shadow,
        shadowOpacity: theme.dark ? 0.28 : 0.10,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 12 },
    },
    setupHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 8,
        paddingHorizontal: 4,
        paddingBottom: 8,
    },
    setupEyebrow: {
        fontSize: 11,
        lineHeight: 14,
        letterSpacing: 0,
        ...Typography.default('semiBold'),
    },
    setupTitle: {
        fontSize: 18,
        lineHeight: 23,
        ...Typography.default('semiBold'),
    },
    setupSubtitle: {
        fontSize: 13,
        lineHeight: 18,
        marginTop: 2,
        ...Typography.default(),
    },
    setupGrid: {
        gap: 7,
    },
    setupCardPressable: {
        borderRadius: 14,
    },
    setupCard: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 10,
        borderRadius: 14,
        padding: 12,
        borderWidth: 1,
    },
    setupCardCompact: {
        paddingVertical: 10,
        paddingHorizontal: 11,
        alignItems: 'center',
    },
    setupIcon: {
        width: 34,
        height: 34,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    setupCardBody: {
        flex: 1,
        minWidth: 0,
    },
    setupCardTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 8,
    },
    setupCardTitle: {
        flex: 1,
        minWidth: 0,
        fontSize: 14,
        lineHeight: 18,
        ...Typography.default('semiBold'),
    },
    setupCardDescription: {
        fontSize: 12,
        lineHeight: 17,
        marginTop: 3,
        ...Typography.default(),
    },
    setupCardValue: {
        fontSize: 14,
        lineHeight: 19,
        marginTop: 8,
        ...Typography.default('semiBold'),
    },
    setupCardValueCompact: {
        marginTop: 4,
        fontSize: 13,
        lineHeight: 17,
    },
    setupChipRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 7,
        marginTop: 6,
    },
    setupChip: {
        minHeight: MINIMUM_TAP_TARGET,
        maxWidth: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 999,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: theme.dark ? 'rgba(255, 255, 255, 0.10)' : theme.colors.glass.border,
        backgroundColor: theme.dark ? 'rgba(255, 255, 255, 0.075)' : theme.colors.accentSoft,
    },
    setupChipText: {
        flexShrink: 1,
        minWidth: 0,
        fontSize: 12,
        lineHeight: 16,
        ...Typography.default('semiBold'),
    },
    setupAgentIcon: {
        width: 14,
        height: 14,
    },
    advancedPanel: {
        marginTop: 9,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: theme.dark ? 'rgba(238, 248, 250, 0.13)' : theme.colors.glass.border,
        backgroundColor: theme.dark ? 'rgba(255, 255, 255, 0.045)' : theme.colors.glass.background,
        overflow: 'hidden',
    },
    advancedHeader: {
        minHeight: MINIMUM_TAP_TARGET,
        paddingHorizontal: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 8,
    },
    advancedTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 7,
        flex: 1,
        minWidth: 0,
    },
    advancedTitle: {
        fontSize: 13,
        lineHeight: 17,
        ...Typography.default('semiBold'),
    },
    advancedPillRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        paddingHorizontal: 10,
        paddingBottom: 10,
        gap: 8,
    },
    advancedPill: {
        minHeight: MINIMUM_TAP_TARGET,
        maxWidth: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 10,
        borderRadius: 999,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: theme.dark ? 'rgba(255, 255, 255, 0.10)' : theme.colors.glass.border,
        backgroundColor: theme.dark ? 'rgba(255, 255, 255, 0.075)' : theme.colors.accentSoft,
    },
    advancedPillText: {
        flexShrink: 1,
        minWidth: 0,
        fontSize: 12,
        lineHeight: 16,
        ...Typography.default('semiBold'),
    },
    advancedExpandedList: {
        gap: 7,
        paddingHorizontal: 8,
        paddingBottom: 8,
    },
    popover: {
        borderRadius: 12,
        paddingVertical: 8,
        marginTop: 8,
        borderWidth: 1,
        borderColor: theme.dark ? 'rgba(255,255,255,0.12)' : theme.colors.divider,
        overflow: 'hidden',
        zIndex: 20,
        ...Platform.select({
            web: {
                boxShadow: '0 4px 20px rgba(0, 0, 0, 0.12)',
            },
            default: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.12,
                shadowRadius: 10,
                elevation: 8,
            },
        }),
    },
    configRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 12,
    },
    configRowWithToggle: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    collapseToggle: {
        minWidth: MINIMUM_TAP_TARGET,
        minHeight: MINIMUM_TAP_TARGET,
        paddingHorizontal: 12,
        paddingVertical: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    collapsedRow: {
        minHeight: MINIMUM_TAP_TARGET,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 12,
    },
    collapsedIconsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 2,
        paddingHorizontal: 4,
        paddingBottom: 8,
    },
    collapsedIconButton: {
        width: MINIMUM_TAP_TARGET,
        height: MINIMUM_TAP_TARGET,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    flashLabel: {
        alignSelf: 'center',
        paddingVertical: 4,
    },
    flashLabelText: {
        fontSize: 12,
        ...Typography.default(),
    },
    configRowPressed: {
        opacity: 0.6,
    },
    agentIcon: {
        width: 15,
        height: 15,
    },
    collapsedAgentIcon: {
        width: 14,
        height: 14,
    },
    configLabel: {
        fontSize: 14,
        color: theme.colors.text,
        ...Typography.default('semiBold'),
        ...Platform.select({ web: { userSelect: 'none' } as any, default: {} }),
    },
    creationStatus: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    creationStatusText: {
        flex: 1,
        minWidth: 0,
    },
    creationStatusTitle: {
        ...Typography.default('semiBold'),
    },
    creationStatusSubtitle: {
        ...Typography.default(),
    },
    inputBox: {
        backgroundColor: theme.colors.glass.raised,
        borderWidth: 1,
        borderColor: theme.colors.glass.border,
        borderRadius: Platform.select({ default: 16, android: 20 }),
        overflow: 'hidden',
        paddingVertical: 2,
        paddingHorizontal: 8,
    },
    inputField: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        paddingLeft: 8,
        paddingRight: 4,
        paddingVertical: 4,
        minHeight: 40,
        gap: 8,
    },
    sendButton: {
        width: COMPOSER_SEND_BUTTON_SIZE,
        height: COMPOSER_SEND_BUTTON_SIZE,
        borderRadius: COMPOSER_SEND_BUTTON_SIZE / 2,
        justifyContent: 'center',
        alignItems: 'center',
        flexShrink: 0,
        marginBottom: COMPOSER_SEND_BUTTON_MARGIN_BOTTOM,
        overflow: 'hidden',
        borderWidth: 1,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 8 },
        elevation: 5,
    },
    sendButtonActive: {
        backgroundColor: theme.colors.button.primary.background,
    },
    sendButtonInactive: {
        backgroundColor: theme.colors.glass.background,
        borderColor: theme.colors.glass.border,
    },
    sendButtonPressable: {
        width: '100%',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
    },
    sendButtonPressed: {
        opacity: 0.78,
    },
    sendButtonGradient: {
        ...StyleSheet.absoluteFillObject,
    },
    sendButtonHighlight: {
        position: 'absolute',
        borderRadius: 999,
    },
    sendButtonSecondaryHighlight: {
        position: 'absolute',
        borderRadius: 999,
    },
    sendButtonIcon: {
        transform: [{ translateX: -1 }, { translateY: 1 }],
    },
    offlineHelp: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 12,
    },
    offlineHelpTitle: {
        fontSize: 13,
        ...Typography.default('semiBold'),
        marginBottom: 4,
    },
    offlineHelpText: {
        fontSize: 12,
        lineHeight: 18,
        ...Typography.default(),
    },
}));

// Bottom sheet styles

// Picker styles
export const pickerStyles = {
    container: {
        paddingHorizontal: 16,
        paddingBottom: 8,
    } as const,
    title: {
        fontSize: 18,
        paddingVertical: 12,
        paddingHorizontal: 4,
        ...Typography.default('semiBold'),
        ...Platform.select({ web: { userSelect: 'none' } as any, default: {} }),
    } as const,
    titleRow: {
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        justifyContent: 'space-between' as const,
    },
    titleActions: {
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        gap: 8,
    },
    modeToggle: {
        flexDirection: 'row' as const,
        borderRadius: 10,
        padding: 2,
        gap: 2,
    },
    modeButton: {
        width: 30,
        height: 26,
        borderRadius: 8,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
    },
    doneButtonPressable: {
        width: 44,
        height: 44,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
    },
    doneButtonGlass: {
        width: 40,
        height: 36,
        borderRadius: 18,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
        overflow: 'hidden' as const,
        borderWidth: 1,
        backgroundColor: 'rgba(255,255,255,0.08)',
    },
    searchRow: {
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        gap: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 12,
        marginBottom: 8,
    },
    searchInput: {
        minHeight: MINIMUM_TAP_TARGET,
        flex: 1,
        fontSize: 15,
        padding: 0,
        ...Typography.default(),
        ...Platform.select({ web: { outlineStyle: 'none' } as any, default: {} }),
    } as const,
    pathInputRow: {
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        gap: 10,
        paddingHorizontal: 12,
        minHeight: 46,
        borderRadius: 12,
        marginBottom: 8,
        borderWidth: 1,
    },
    pathInputField: {
        flex: 1,
    } as const,
    pathTextInput: {
        fontSize: 16,
        minHeight: 44,
        paddingVertical: 0,
        ...Typography.default(),
        ...Platform.select({
            android: { textAlignVertical: 'center' as const },
            web: { outlineStyle: 'none' } as any,
            default: {},
        }),
    } as const,
    pathMetaText: {
        fontSize: 13,
        paddingHorizontal: 4,
        paddingBottom: 8,
        ...Typography.default(),
        ...Platform.select({ web: { userSelect: 'none' } as any, default: {} }),
    } as const,
    sectionLabel: {
        fontSize: 13,
        paddingHorizontal: 4,
        paddingBottom: 8,
        ...Typography.default('semiBold'),
        ...Platform.select({ web: { userSelect: 'none' } as any, default: {} }),
    } as const,
    option: {
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        gap: 12,
        paddingHorizontal: 12,
        paddingVertical: 12,
        borderRadius: 12,
    },
    optionPressed: {
        opacity: 0.6,
    } as const,
    optionText: {
        fontSize: 15,
        ...Typography.default(),
        ...Platform.select({ web: { userSelect: 'none' } as any, default: {} }),
    } as const,
    divider: {
        height: 1,
        marginHorizontal: 12,
        marginVertical: 4,
    } as const,
    optionList: {
        flexGrow: 0,
        flexShrink: 1,
    } as const,
    emptyText: {
        fontSize: 14,
        textAlign: 'center' as const,
        paddingVertical: 20,
        ...Typography.default(),
        ...Platform.select({ web: { userSelect: 'none' } as any, default: {} }),
    } as const,
    offlineHint: {
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
        paddingVertical: 32,
        paddingHorizontal: 16,
        borderRadius: 12,
        gap: 8,
    },
    offlineHintText: {
        fontSize: 14,
        textAlign: 'center' as const,
        ...Typography.default(),
    } as const,
};
