import { describe, expect, it } from 'vitest';
import { agentHubConfigManifest } from './configManifest';

describe('AgentHub platform config manifest', () => {
    it('locks Expo brand variants, bundle ids, and version for AgentHub 1.0', () => {
        expect(agentHubConfigManifest.expo).toEqual({
            slug: 'agenthub',
            scheme: 'agenthub',
            version: '1.0.0',
            runtimeVersion: '1',
            variants: {
                development: {
                    name: 'AgentHub (dev)',
                    bundleIdentifier: 'com.artsum.agenthub.dev',
                },
                preview: {
                    name: 'AgentHub (preview)',
                    bundleIdentifier: 'com.artsum.agenthub.preview',
                },
                production: {
                    name: 'AgentHub',
                    bundleIdentifier: 'com.artsum.agenthub',
                },
            },
        });
    });

    it('locks native Android production identifiers generated by Expo prebuild', () => {
        expect(agentHubConfigManifest.androidProduction).toEqual({
            appName: 'AgentHub',
            applicationId: 'com.artsum.agenthub',
            namespace: 'com.artsum.agenthub',
            versionName: '1.0.0',
        });
    });

    it('locks Tauri product names, identifiers, and window titles', () => {
        expect(agentHubConfigManifest.tauri).toEqual({
            production: {
                productName: 'AgentHub',
                identifier: 'com.artsum.agenthub',
                title: 'AgentHub',
                version: '1.0.0',
            },
            preview: {
                productName: 'AgentHub (preview)',
                identifier: 'com.artsum.agenthub.preview',
                title: 'AgentHub (preview)',
            },
            development: {
                productName: 'AgentHub (dev)',
                identifier: 'com.artsum.agenthub.dev',
                title: 'AgentHub (dev)',
            },
        });
    });
});
